Widget/rework of card design
Mil0dV/co2ok-dojo-2.0 pull request #39
Opened 2020-09-22 13:12 UTC by jdsmith022

Redesign of hover card 

current size: 350 X 435
added new pngs designed specifically for douchezaak.nl
final copy still needs to be confirmed and added

minor adjustment to placeWidgetInfoBox to ensure the card is not clipped on different res

current design:

<img width="471" alt="Screen Shot 2020-09-22 at 3 11 45 PM" src="https://user-images.githubusercontent.com/45078521/93886674-07b1ec80-fce6-11ea-931a-d4ca661e42e4.png">
<img width="432" alt="Screen Shot 2020-09-22 at 3 11 30 PM" src="https://user-images.githubusercontent.com/45078521/93886690-0bde0a00-fce6-11ea-97a2-e54a1504d623.png">

2020-09-22 13:45 UTC, Mil0dV requested changes
Looks good to me!

2020-09-22 13:45 UTC, Mil0dV commented on frontend/public/widget/co2okWidgetMark-519dc2a3.js
> +      let window_width = jQuery(window).width();
As discussed, these 2 lines can be removed

2020-09-25 10:43 UTC, jdsmith022 commented
<img width="403" alt="Screen Shot 2020-09-25 at 12 19 35 PM" src="https://user-images.githubusercontent.com/45078521/94258137-afb8f700-ff2c-11ea-8f46-e3b9063ecae3.png">

<img width="1680" alt="Screen Shot 2020-09-25 at 12 19 45 PM" src="https://user-images.githubusercontent.com/45078521/94258124-a9c31600-ff2c-11ea-8f9e-16e83c36ca1b.png">

2020-09-25 12:28 UTC, Ghostyfied approved these changes
No changes needed from my end.

2020-09-29 12:59 UTC, closed without merging