Feat/updated store and team
Mil0dV/co2ok-dojo-2.0 pull request #46
Opened 2020-10-28 14:15 UTC by jdsmith022

updated the store logos on the landing page and for /webshops. A link to /webshops has been added to navBar in CO2 compensation dropdown menu

refactor a bit: 
/src/views/webshops/Webshops.vue (aka /webshops page) now imports component /src/components/layout/Webshops.vue

this makes it easier to update the webshop logos. If srcs/components/layout/Webshops.vue is updated, then logos are updated in /src/views/webshops/Webshops.vue

new navbar link to /webshops :
<img width="2735" alt="Screenshot 2020-10-28 at 15 08 48" src="https://user-images.githubusercontent.com/45078521/97447269-abb73500-192f-11eb-8efb-9f3d23bb00a5.png">

2020-10-28 15:25 UTC, jdsmith022 commented
added more shops:
<img width="1175" alt="Screenshot 2020-10-28 at 16 25 01" src="https://user-images.githubusercontent.com/45078521/97457602-31d87900-193a-11eb-86b4-fe934a87a389.png">

2020-10-28 16:15 UTC, Mil0dV commented
I could have mentioned this earlier, but could you move these up:
- Naif
- Willicroft
- degroenelinde 
- urban goddess

You could swap them with dimlight <-> millers oils

2020-10-28 16:23 UTC, Mil0dV requested changes
Modal/component code looks a lot cleaner like this. Just the 2 small items mentioned before and it's good2go!

2020-10-28 16:23 UTC, Mil0dV commented on frontend/src/components/layout/Webshops.vue
> +                        link: 'https://fairbow.myshopify.com/'
=> https://fairbowusa.com/

2020-10-29 07:22 UTC, jdsmith022 commented
<img width="973" alt="Screenshot 2020-10-29 at 08 20 46" src="https://user-images.githubusercontent.com/45078521/97537908-d81a9200-19bf-11eb-9eeb-e0e9b7d0b283.png">

2020-11-10 12:25 UTC, merged